name: deploy_to_cocoapods

on:
  push:
    tags:
      - '*'
  
jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
