name: deploy_to_cocoapods

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 22 * * *' #每天在国际标准时间22点（北京时间早上6点）运行。
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'checkout codes'
      uses: actions/checkout@v1
    - name: get weather report
      run: |
        curl -H "Accept-Language: zh-CN" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36" -o result.html wttr.in/xian
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: xian Weather Report
        body: file://result.html
        to: 317476057@163.com
        from: GitHub Actions
        content_type: text/html
