name: test_version

on: [push, pull_request]
#on:
#  check_run:
#    types: [rerequested, requested_action]
    
    
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Dump steps context
        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TILT_CONTEXT: ${{ github.event.release.name }}
        run: |
          echo "Hello ${{ github.event.release.name }}!"
#          echo "json -- $GITHUB_CONTEXT"
          echo "jsonttle -- $GITHUB_TILT_CONTEXT"
        
      
#jobs:
#  save-version:
#    runs-on: ubuntu-latest
#    steps:
#    - name: 'checkout codes'
#      uses: actions/checkout@v1
#    - name: pull version
#      run: |
#        #!/bin/sh
#
#        git clone https://$IOT_GITHUB_ACCESS_TOKEN@github.com/tonychanchen/iot-version.git
#        cd iot-version
#        echo 5 > iot-version-android.txt
#
#        git add .
#        git commit -m "test"
#        git push
